[package]
name = "rust_lib_ark_flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1"
ark-bdk-wallet = { git = "https://github.com/coblox/ark-rs.git", rev = "12c1c0647bf4b4a2b13b9590c5c8a7205f2f2a4a" }
ark-rs = { git = "https://github.com/coblox/ark-rs.git", features = ["client"], rev = "12c1c0647bf4b4a2b13b9590c5c8a7205f2f2a4a" }
bitcoin = { version = "0.32.4", features = ["rand"] }
esplora-client = { version = "0.11.0", features = ["async-https", "blocking-https"] }
flutter_rust_bridge = { version = "=2.9.0", features = ["anyhow"] }
futures = "0.3.31"
hex = "0.4"
nostr = { version = "0.40.0", default-features = false, features = ["std"] }
parking_lot = { version = "0.12.1" }
rand = "0.8.5"
rand_chacha = "0.9.0"
regex = "1"
state = "0.6.0"
tracing = "0.1.37"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "env-filter", "time", "json"] }
url = "2.5.4"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
